### ISSUE TITLE
GitHub action fails with semantic_release.errors.GitPushError: Failed to push branch (main) to remote

### ISSUE THREAD

**Issue by kierun** [python-semantic-release/python-semantic-release#1127]
### Description

The release is created fine. However, the default GitHub action fails with semantic_release.errors.GitPushError: Failed to push branch (main) to remote

### Expected behavior

I expect it to push tags and changes after a release is created.

### Actual behavior

I get the following error:

```bash
[…]
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/commands/version.py", line 680, in version
    project.git_(push_branch(
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/gitproject.py", line 233, in git_push_branch
    raise GitPushError(
semantic_release.errors.GitPushError: Failed to push branch (main) to remote
```

Full [logs here](https://github.com/kierun/pynpc/actions/runs/12432297862/job/34711398652)

### Environment

None of those are relevant since I am using the default GitHub action…

<details>
<summary><code>pip freeze</code></summary>

N.A.

</details>

<br>

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

N.A.

</details>

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install uv && uv build"
```

</details>
<br>

<details>
<summary>Build System Configuration</summary>

[Full `pyproject.toml` file here](https://github.com/kierun/pynpc/blob/main/pyproject.toml)

I am pretty sure it's not a problem…

</details>
<br>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          push: true
          root_options: -vv

```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv <i>command</i></code></summary>

```log
Build completed successfully!
[13:29:41] DEBUG    [cmd.execute] Popen(['git', 'add',               cmd.py:1253
                    '/github/workspace/CHANGELOG.md'],                          
                    cwd=/github/workspace, stdin=None, shell=False,             
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'add',               cmd.py:1253
                    'pyproject.toml'], cwd=/github/workspace,                   
                    stdin=None, shell=False,                                    
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'cat-file',          cmd.py:1253
                    '--batch-check'], cwd=/github/workspace,                    
                    stdin=<valid stream>, shell=False,                          
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'diff', '-R',        cmd.py:1253
                    '4ef68241ee272214efbb81781887011021a905ca',                 
                    '--cached', '--abbrev=40', '--full-index', '-M',            
                    '--raw', '-z', '--no-color'],                               
                    cwd=/github/workspace, stdin=None, shell=False,             
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'diff', '--cached',  cmd.py:1253
                    '--abbrev=40', '--full-index', '--raw'],                    
                    cwd=/github/workspace, stdin=None, shell=False,             
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'commit', '-m',      cmd.py:1253
                    '0.4.0\n\nAutomatically generated by                        
                    python-semantic-release', '--date=1734701379'],             
                    cwd=/github/workspace, stdin=None, shell=False,             
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'tag', '-m',         cmd.py:1253
                    'v0.4.0', '-a', 'v0.4.0'],                                  
                    cwd=/github/workspace, stdin=None, shell=False,             
                    universal_newlines=False)                                   
           DEBUG    [cmd.execute] Popen(['git', 'push',              cmd.py:1253
                    '***github.com/kierun/pynpc.git            
                    ', 'main'], cwd=/github/workspace, stdin=None,              
                    shell=False, universal_newlines=False)                      
           ERROR    [gitproject.git_push_branch] Cmd('git')    gitproject.py:232
                    failed due to: exit code(1)                                 
                      cmdline: git push                                         
                    ***github.com/kierun/pynp                  
                    c.git main                                                  
                      stderr: 'error: src refspec main matches                  
                    more than one                                               
                    error: failed to push some refs to                          
                    'https://github.com/kierun/pynpc.git''                      
                    ╭── Traceback (most recent call last) ───╮                  
                    │ /psr/.venv/lib/python3.12/site-package │                  
                    │ s/semantic_release/gitproject.py:230   │                  
                    │ in git_push_branch                     │                  
                    │                                        │                  
                    │   227 │   │                            │                  
                    │   228 │   │   with Repo(str(self.proje │                  
                    │   229 │   │   │   try:                 │                  
                    │ ❱ 230 │   │   │   │   repo.git.push(re │                  
                    │   231 │   │   │   except GitCommandErr │                  
                    │   232 │   │   │   │   self.logger.exce │                  
                    │   233 │   │   │   │   raise GitPushErr │                  
                    │                                        │                  
                    │ /psr/.venv/lib/python3.12/site-package │                  
                    │ s/git/cmd.py:986 in <lambda>           │                  
                    │                                        │                  
                    │    983 │   │   """                     │                  
                    │    984 │   │   if name.startswith("_") │                  
                    │    985 │   │   │   return super().__ge │                  
                    │ ❱  986 │   │   return lambda *args, ** │                  
                    │    987 │                               │                  
                    │    988 │   def set_persistent_git_opti │                  
                    │    989 │   │   """Specify command line │                  
                    │                                        │                  
                    │ /psr/.venv/lib/python3.12/site-package │                  
                    │ s/git/cmd.py:1598 in _call_process     │                  
                    │                                        │                  
                    │   1595 │   │   call.append(dashify(met │                  
                    │   1596 │   │   call.extend(args_list)  │                  
                    │   1597 │   │                           │                  
                    │ ❱ 1598 │   │   return self.execute(cal │                  
                    │   1599 │                               │                  
                    │   1600 │   def _parse_object_header(se │                  
                    │   1601 │   │   """                     │                  
                    │                                        │                  
                    │ /psr/.venv/lib/python3.12/site-package │                  
                    │ s/git/cmd.py:1388 in execute           │                  
                    │                                        │                  
                    │   1385 │   │   # END handle debug prin │                  
                    │   1386 │   │                           │                  
                    │   1387 │   │   if with_exceptions and  │                  
                    │ ❱ 1388 │   │   │   raise GitCommandErr │                  
                    │   1389 │   │                           │                  
                    │   1390 │   │   if isinstance(stdout_va │                  
                    │        output_stream.                  │                  
                    │   1391 │   │   │   stdout_value = safe │                  
                    ╰────────────────────────────────────────╯                  
                    GitCommandError: Cmd('git') failed due to:                  
                    exit code(1)                                                
                      cmdline: git push                                         
                    ***github.com/kierun/pynp                  
                    c.git main                                                  
                      stderr: 'error: src refspec main matches                  
                    more than one                                               
                    error: failed to push some refs to                          
                    'https://github.com/kierun/pynpc.git''                      
Traceback (most recent call last):
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/gitproject.py", line 230, in git_push_branch
    repo.git.push(remote_url, branch)
  File "/psr/.venv/lib/python3.12/site-packages/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push ***github.com/kierun/pynpc.git main
  stderr: 'error: src refspec main matches more than one
error: failed to push some refs to 'https://github.com/kierun/pynpc.git''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/psr/.venv/bin/semantic-release", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/commands/version.py", line 680, in version
    project.git_push_branch(
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/gitproject.py", line 233, in git_push_branch
    raise GitPushError(
semantic_release.errors.GitPushError: Failed to push branch (main) to remote
```

</details>

### Additional context

[Please don't hesitate to look at the action here](https://github.com/kierun/pynpc/actions/runs/12432297862)

**Comment by codejedi365** [comment]
@kierun, very curious of an issue.  I think the primary issue is the git error that was thrown and I don't think it resides within the PSR action.

```log
error: src refspec main matches more than one
```

My limited understanding of this error is that you likely have another branch, tag or other git reference that also starts with the word `main` (could be `maintain`). The git command doesn't seem to grab an exact match but rather a starts with match and went it returns more than one result you get this error as git doesn't know which one you want.

I looked at your repo and I didn't see another branch so I felt that was odd (could be a tag then). Your GitHub action steps looked fine to check out the correct branch with a full history. These errors are more common on GitLab as GitLab does a poor job of cleaning repos when build caches are enabled.

**Comment by codejedi365** [comment]
Separately, I think your semantic release configuration is out of date as it has some keys that are pre-v8 which no longer exist. Recommend reviewing the V8 migration documentation on the docs site and also looking into the `generate-config` command to build a new config and merge it with your old settings. Note that it will just list out all defaults. You do not need to provide all defaults if you would rather PSR manage it internally. PSR will use your config settings as overrides to the defaults (ie if it's not specified PSR loads the default).

**Comment by kierun** [comment]
@codejedi365 Thank you!

I updated the configuration (I just picked all the defaults for now, as they work for me™) and committed that.

I added some debugging output about tags and branches. Here is what I see — [Full report](https://github.com/kierun/pynpc/actions/runs/12457019428):

![screenshot](https://github.com/user-attachments/assets/5882cae7-b1d0-4fbc-8177-11f66b762195)

Oh look, a tag called `main`… :rage:  Deleted that (it was as release called `main` which was odd…), and ran the action again. 

:cry: Sadly, it failed once more with the same error:

```bash
semantic_release.errors.GitPushError: Failed to push branch (main) to remote
```

**Comment by kierun** [comment]
AHA!

```
To https://github.com/kierun/pynpc.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/kierun/pynpc.git''
```

This would do it too! :facepalm: 

How do I keep the branch protection with allowing the GHA action to commit to `main`?

**Comment by codejedi365** [comment]
@kierun which branch protections do you have configured?

**Comment by kierun** [comment]
> @kierun which branch protections do you have configured?

- `Require a pull request before merging` as well.
- Force push are allowed, but just from myself.

**Comment by codejedi365** [comment]
The simplest thing to do is to set `commit: false`. Which will turn off creating a commit and attempting to push which will hit your first rule. But obviously that has side effects especially regarding a changelog update.

There is not a current feature to toggle force push and I am very reluctant to implement one.

There is also not an implementation to have PSR open a pull request so there are limited options. You probably can get creative with the CI to do all but release in the PR workflow so then there is no need for a commit upon release. 

I hear some people handle this situation more with a GitHub App instead but I have never done that.

**Comment by kierun** [comment]
Removed the branch protection… Semantic release worked. I'll move to a CI/CD development model. All good. 

Your assistance is greatly appreciated.

**Comment by kierun** [comment]
@codejedi365 Oh, I have a new tag called `main`. I guess the semantic release is creating that. Can I stop it from doing this?

**Comment by codejedi365** [comment]
> @codejedi365 Oh, I have a new tag called `main`. I guess the semantic release is creating that. Can I stop it from doing this?

PSR doesn't know how to make a tag called main unless you modified the tag format parameter. Not sure how that is happening

**Comment by kierun** [comment]
> > @codejedi365 Oh, I have a new tag called `main`. I guess the semantic release is creating that. Can I stop it from doing this?
> 
> PSR doesn't know how to make a tag called main unless you modified the tag format parameter. Not sure how that is happening

Ah, well… I think I'll do releases manually until the whole process just works. 

Again, thank you so much for your assistance. :pray:

**Comment by codejedi365** [comment]
> Ah, well… I think I'll do releases manually until the whole process just works. 

Is PSR not fully working? Did you make sure that the main tag was removed from the remote? If you are using the CI it's possible that your runner is caching the repo directory and not removing the tag? 

You must specifically prune tags if the last one is the case.

**Comment by kierun** [comment]
> > Ah, well… I think I'll do releases manually until the whole process just works.
> 
> Is PSR not fully working? Did you make sure that the main tag was removed from the remote? If you are using the CI it's possible that your runner is caching the repo directory and not removing the tag?
> 
> You must specifically prune tags if the last one is the case.

There is a `main` tag being created, somehow. I have not set it up (I think! ¯\\_(ツ)\_/¯) 

I'll have a better look this week as I've been off with the family over Xmas…

Thank you so much for your help. It is very much appreciated.
