### ISSUE TITLE
Don’t tag before distributions have been built to avoid incomplete release

### ISSUE THREAD

**Issue by jenstroeger** [python-semantic-release/python-semantic-release#426]
## The problem

Logs are most useful, so here is mine:
```
debug: set_new_version('2.2.0')
debug: Writing new version number: path=PosixPath('src/package/__init__.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+(?:\\.\\d+)?)["\\\']' num_matches=1
debug: set_new_version -> True
debug: commit_new_version('2.2.0')
debug: commit_new_version -> [main 828eb2a] Release v2.2.0
debug:  2 files changed, 10 insertions(+), 1 deletion(-)
debug: tag_new_version('2.2.0')
debug: tag_new_version -> 
Bumping with a minor version to 2.2.0
Pushing new version
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Github'>
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Github'>
debug: push_new_version(, auth_token='***', owner='owner', name='name', branch=main, domain='github.com')
```
So far so good, the repo was updated and the commit is now tagged.

Then…
```
Building distributions
debug: Removing build folder: `dist`
Running python setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "/github/workspace/setup.py", line 61, in <module>
    # some line of code
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    # some line of code
ValueError: Something happened when building the distribution
error: Encountered a bad command exit code!
error: 
error: Command: 'python setup.py sdist bdist_wheel'
error: 
error: Exit code: 1
error: 
error: Stdout: already printed
error: 
error: Stderr: already printed
error: 
```
At this point the Github Action fails, but the release was still tagged.

## Expected behavior

_Do not tag_ the commits before all distribution artifacts have been built successfully.

**Comment by codejedi365** [comment]
Version `8+` maintains building distribution artifacts prior to any tag or commits.
