### ISSUE TITLE
Missing encoding when reading config with emojis

### ISSUE THREAD

**Issue by beatreichenbach** [python-semantic-release/python-semantic-release#584]
## The problem

Ran `semantic-release version --noop`  and got this error since the last emoji update.

Python 3.10.10
python-semantic-release    7.33.3

```
(venv) >semantic-release version --noop       
Traceback (most recent call last):
  File "C:\Program Files\Python 3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python 3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "venv\Scripts\semantic-release.exe\__main__.py", line 4, in <module>
  File "venv\lib\site-packages\semantic_release\cli.py", line 14, in <module>
    from .changelog import markdown_changelog
  File "venv\lib\site-packages\semantic_release\changelog\__init__.py", line 5, in <module>
    from ..settings import config, current_changelog_components
  File "venv\lib\site-packages\semantic_release\settings.py", line 81, in <module>
    config = _config()
  File "venv\lib\site-packages\semantic_release\settings.py", line 26, in _config
    ini_config = _config_from_ini(ini_paths)
  File "venv\lib\site-packages\semantic_release\settings.py", line 37, in _config_from_ini
    parser.read(paths)
  File "C:\Program Files\Python 3.10\lib\configparser.py", line 699, in read
    self._read(fp, filename)
  File "C:\Program Files\Python 3.10\lib\configparser.py", line 1022, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Program Files\Python 3.10\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1301: character maps to <undefined>
```

**Comment by beatreichenbach** [comment]
Changing settings.py #37 `    parser.read(paths, encoding='utf-8')` does work for me.

**Comment by bernardcooke53** [comment]
Hi @beatreichenbach @Gazzzzyy :wave:

Are you able to work around this by setting [`PYTHONUTF8`](https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONUTF8)?

```cmd
set PYTHONUTF8=1
```

This does need looking at but hopefully that will fix the issue in the short-term for you :crossed_fingers: - I'm afraid I don't have a Windows machine to hand to test with

**Comment by MichalVasut** [comment]
@bernardcooke53 yop, this should work in shortterm, I've used it recently at different tool.

**Comment by beatreichenbach** [comment]
Yep, thank you.
And the code @MichalVasut provided should work, I'm happy to test it on my Windows machine for you if you wanna integrate his code on a different branch.

**Comment by MichalVasut** [comment]
> Yep, thank you. And the code @MichalVasut provided should work, I'm happy to test it on my Windows machine for you if you wanna integrate his code on a different branch.

It's not my code, it's extract from existing code where it shows that the `read` method uses python internal `open` function that should be supplied with encoding - in this case `utf-8` - in order to work correctly on windows.

Check this article: https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

**Comment by Tony-Feng** [comment]
> 

Hi @bernardcooke53, this will also temporarily fix `UnicodeDecodeError` issue in a Windows Conda env:
```
>>> semantic-release version --noop
Traceback (most recent call last):
  File "\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\Scripts\semantic-release.exe\__main__.py", line 4, in <module>
  File "\lib\site-packages\semantic_release\cli.py", line 14, in <module>
    from .changelog import markdown_changelog
  File "\lib\site-packages\semantic_release\changelog\__init__.py", line 5, in <module>
    from ..settings import config, current_changelog_components
  File "\lib\site-packages\semantic_release\settings.py", line 81, in <module>
    config = _config()
  File "\lib\site-packages\semantic_release\settings.py", line 26, in _config
    ini_config = _config_from_ini(ini_paths)
  File "\lib\site-packages\semantic_release\settings.py", line 37, in _config_from_ini
    parser.read(paths)
  File "\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 8: illegal multibyte sequence
```

Looking forward to the new release to include the fix for this 😄

**Comment by bernardcooke53** [comment]
#596 if anyone would like to try with that :pray:

**Comment by Tony-Feng** [comment]
> #596 if anyone would like to try with that 🙏

Hi @bernardcooke53, I tried `semantic-release version --noop -v DEBUG`, it worked on my end, in a Windows Conda env with Python 3.8.16 and lib from your branch, waiting for more feedbacks 😉

**Comment by bernardcooke53** [comment]
Grateful for the sanity check @Tony-Feng, I've merged the PR now - other problems can always be raised in a new issue :slightly_smiling_face:

**Comment by beatreichenbach** [comment]
A little late but just wanted to confirm it worked on my end too with [v7.34.2](https://github.com/python-semantic-release/python-semantic-release/releases/tag/v7.34.2) in Python 3.10, thank you so much @bernardcooke53
