### ISSUE TITLE
ValueError: some required outputs were not set: released, version

### ISSUE THREAD

**Issue by claverru** [python-semantic-release/python-semantic-release#611]
## The problem

On version 8.0.0-rc1

```bash
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1[13](https://github.com/ChartBoost/bidder-vm-template/actions/runs/5312950302/jobs/9618175976#step:5:14)0, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line [16](https://github.com/ChartBoost/bidder-vm-template/actions/runs/5312950302/jobs/9618175976#step:5:17)56, in invoke
    with sub_ctx:
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 461, in __exit__
    self.close()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 590, in close
    self._exit_stack.close()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 584, in close
    self.__exit__(None, None, None)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 449, in _exit_wrapper
    callback(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/semantic_release/cli/github_actions_output.py", line 74, in write_if_possible
    f.write(self.to_output_text())
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/semantic_release/cli/github_actions_output.py", line 56, in to_output_text
    raise ValueError(
ValueError: some required outputs were not set: released, version
```

Workflow:
```yaml
name: Semantic Release
on: push

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - run: pip install python-semantic-release==8.0.0-rc1

      - run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            semantic-release version
          else
            semantic-release version --build-metadata ${{ github.ref }}
          fi
        env:
          GH_TOKEN: ${{ github.token }}
```

pyproject.toml
```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.dev]
match = "^(?!main$).*"
prerelease_token = "rc"
prerelease = true
```

**Comment by bernardcooke53** [comment]
@claverru this is a bit concerning - the only way I can see this happening is if there's an error between [setting the callback](https://github.com/python-semantic-release/python-semantic-release/blob/eb8d53cc86dd54041ed2b66868a8a7f91bf6bb0a/semantic_release/cli/commands/version.py#L233) and [setting the defaults](https://github.com/python-semantic-release/python-semantic-release/blob/eb8d53cc86dd54041ed2b66868a8a7f91bf6bb0a/semantic_release/cli/commands/version.py#L287), which would point at [`next_version`](https://github.com/python-semantic-release/python-semantic-release/blob/eb8d53cc86dd54041ed2b66868a8a7f91bf6bb0a/semantic_release/cli/commands/version.py#L276) - could be tough to reproduce as it's dependent on commit history.

Is there a way you can re-run the action with `semantic-release -vv version` and post the output? I have a suspicion that the traceback is hiding another error that happened earlier :grimacing:. Maybe a good idea in either case to move setting the callback until after setting the defaults - that way another error will cause an exit without invoking it and the workflow will fail before any subsequent steps try to use it (thinking out loud a bit)
