### ISSUE TITLE
`semantic-release version` crashes with `InvalidVersion` exception

### ISSUE THREAD

**Issue by css-optivoy** [python-semantic-release/python-semantic-release#626]
## The problem

Running `semantic-release version` crashes with an exception:

```
$ semantic-release version
[10:25:08] WARNING  [semantic_release.cli.config] WARNING config.from_raw_config: the token for the remote VCS is configured   config.py:353
                    as stored in the GH_TOKEN environment variable, but it is empty
Traceback (most recent call last):
  File "/.../bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "/.../lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/.../lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/.../lib/python3.10/site-packages/semantic_release/cli/commands/version.py", line 274, in version
    new_version = next_version(
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 224, in next_version
    all_git_tags_as_versions = tags_and_versions(repo.tags, translator)
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 37, in tags_and_versions
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 37, in <listcomp>
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/.../lib/python3.10/site-packages/semantic_release/version/translator.py", line 75, in from_tag
    return self.from_string(raw_version_str)
  File "/.../lib/python3.10/site-packages/semantic_release/version/translator.py", line 56, in from_string
    return Version.parse(
  File "/.../lib/python3.10/site-packages/semantic_release/version/version.py", line 129, in parse
    raise InvalidVersion(f"{version_str!r} is not a valid Version")
semantic_release.version.version.InvalidVersion: 'azure-0.1.0' is not a valid Version
```

## Expected behavior

The version should be incremented.
Or at the least it should provide a user friendly error message, and not an exception with a stack trace.

## Environment

```shell
$ uname -a
Linux hostname 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 3.10.6

$ pip --version
pip 22.3 from /.../lib/python3.10/site-packages/pip (python 3.10)

$ semantic-release --version
semantic-release, version 8.0.0

$ pip freeze
affine==2.4.0
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
autoflake==2.2.0
azure-core==1.28.0
azure-identity==1.13.0
azure-storage-queue==12.6.0
bcrypt==4.0.1
black==23.7.0
build==0.10.0
CacheControl==0.12.11
cachetools==5.3.1
Cartopy==0.21.1
certifi==2023.5.7
cffi==1.15.1
cfgv==3.3.1
cftime==1.6.2
chardet==5.1.0
charset-normalizer==3.2.0
cleo==2.0.1
click==8.1.5
click-plugins==1.1.1
cligj==0.7.2
cmake==3.25.0
colorama==0.4.6
contourpy==1.1.0
crashtest==0.4.1
cryptography==41.0.2
cycler==0.11.0
Cython==0.29.36
db-dtypes==1.1.1
deap==1.3.3
deptry==0.12.0
distlib==0.3.6
dotty-dict==1.3.1
dulwich==0.21.5
exceptiongroup==1.1.2
filelock==3.12.2
Fiona==1.9.4.post1
flake8==6.0.0
fonttools==4.41.0
frozenlist==1.4.0
GeoAlchemy2==0.14.0
geographiclib==2.0
geopandas==0.13.2
geopy==2.3.0
gitdb==4.0.10
GitPython==3.1.32
google-api-core==2.11.1
google-auth==2.22.0
google-cloud-bigquery==3.11.3
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.59.1
greenlet==2.0.2
grpcio==1.56.0
grpcio-status==1.56.0
html5lib==1.1
identify==2.5.24
idna==3.4
igraph==0.10.6
importlib-metadata==6.8.0
importlib-resources==5.7.0
iniconfig==2.0.0
installer==0.7.0
isodate==0.6.1
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
joblib==1.3.1
jsonschema==4.18.3
jsonschema-specifications==2023.6.1
keyring==23.13.1
kiwisolver==1.4.4
lit==15.0.7
lockfile==0.12.2
lxml==4.9.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mccabe==0.7.0
mdurl==0.1.2
more-itertools==9.1.0
mpmath==1.2.1
msal==1.22.0
msal-extensions==1.0.0
msgpack==1.0.5
multidict==6.0.4
mypy-extensions==1.0.0
netCDF4==1.6.4
networkx==3.0
nodeenv==1.8.0
numpy==1.25.1
opencensus==0.11.2
opencensus-context==0.1.3
opencensus-ext-azure==1.1.9
packaging==23.1
pandas==1.5.3
paramiko==2.12.0
pathspec==0.11.1
pexpect==4.8.0
Pillow==9.5.0
pkginfo==1.9.6
platformdirs==3.9.1
pluggy==1.2.0
poetry==1.5.1
poetry-core==1.6.1
poetry-plugin-export==1.4.0
portalocker==2.7.0
pre-commit==2.21.0
proto-plus==1.22.3
protobuf==4.23.4
psutil==5.9.5
psycopg2-binary==2.9.6
ptyprocess==0.7.0
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pycparser==2.21
pydantic==1.10.11
pyflakes==3.0.1
Pygments==2.15.1
pygrib==2.1.4
PyJWT==2.7.0
pykml==0.2.0
PyNaCl==1.5.0
pyodbc==4.0.34
pyparsing==3.0.9
pyproj==3.6.0
pyproject-api==1.5.3
pyproject_hooks==1.0.0
pyshp==2.3.1
pytest==7.4.0
pytest-mpl==0.16.1
python-dateutil==2.8.2
python-gitlab==3.15.0
python-semantic-release==8.0.0
pytorch-triton-rocm==2.0.1
pytz==2023.3
PyYAML==6.0
rapidfuzz==2.15.1
rasterio==1.3.8
referencing==0.29.1
requests==2.31.0
requests-toolbelt==1.0.0
rich==13.4.2
rpds-py==0.8.10
rsa==4.9
scikit-learn==1.3.0
scipy==1.11.1
SecretStorage==3.3.3
Shapely==1.8.5.post1
shellingham==1.5.0.post1
six==1.16.0
slack-sdk==3.21.3
slackclient==2.9.4
smmap==5.0.0
snuggs==1.4.7
SQLAlchemy==2.0.19
sympy==1.11.1
texttable==1.6.7
threadpoolctl==3.2.0
tomli==2.0.1
tomlkit==0.11.8
torch==2.0.0+rocm5.4.2
torchaudio==2.0.1+rocm5.4.2
torchvision==0.15.1+rocm5.4.2
tox==4.6.4
trove-classifiers==2023.7.6
typing_extensions==4.7.1
urllib3==1.26.16
virtualenv==20.24.0
webencodings==0.5.1
xarray==0.21.1
xgboost==1.7.6
xlrd==2.0.1
XlsxWriter==3.1.2
yarl==1.9.2
zipp==3.16.2
```

## Configuration

`pyproject.toml`:
```toml

[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]
branch = "production"
changelog_file = "CHANGELOG.md"
build_command = "poetry build"
dist_path = "dist/"
upload_to_release = true
upload_to_repository = false
remove_dist = false
patch_without_tag = true
tag_format = "{version}"
prerelease_tag = "dev"

[tool.semantic_release.branches.main]
match = ".*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# ...
```

## Logs

```shell
$ semantic-release -vv version
[11:50:53] DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: logging level set to: DEBUG                            main.py:106
           DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: global cli options:                                    main.py:124
                    GlobalCommandLineOptions(noop=False, verbosity=2, config_file='pyproject.toml', strict=False)                           
           INFO     [semantic_release.cli.commands.main] INFO main.main: Loading TOML configuration from pyproject.toml          main.py:128
           INFO     [semantic_release.cli.config] INFO config.select_branch_options: Using group 'main' options, as '.*'       config.py:250
                    matches 'test'                                                                                                          
           WARNING  [semantic_release.cli.config] WARNING config.from_raw_config: the token for the remote VCS is configured   config.py:353
                    as stored in the GH_TOKEN environment variable, but it is empty                                                         
           DEBUG    [semantic_release.changelog.template] DEBUG template.environment: {'template_dir': 'templates',           template.py:51
                    'block_start_string': '{%', 'block_end_string': '%}', 'variable_start_string': '{{',                                    
                    'variable_end_string': '}}', 'comment_start_string': '{#', 'comment_end_string': '#}',                                  
                    'line_statement_prefix': None, 'line_comment_prefix': None, 'trim_blocks': False, 'lstrip_blocks': False,               
                    'newline_sequence': '\n', 'keep_trailing_newline': False, 'extensions': (), 'autoescape': True,                         
                    'autoescape_value': True}                                                                                               
           DEBUG    [semantic_release.version.translator] DEBUG translator._invert_tag_format_to_re: inverted tag_format    translator.py:40
                    '{version}' to '(?P<version>.*)'                                                                                        
           DEBUG    [semantic_release.cli.commands.version] DEBUG version.is_forced_prerelease: force_prerelease = False,      version.py:48
                    force_level = None, prerelease = False                                                                                  
           DEBUG    [semantic_release.version.version] DEBUG version.parse: attempting to parse string '0.1.0' as Version     version.py:126
           DEBUG    [semantic_release.version.version] DEBUG version.parse: version string 0.1.0 parsed as a non-prerelease   version.py:148
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed build metadata '' from version string      version.py:151
                    0.1.0                                                                                                                   
           DEBUG    [semantic_release.version.version] DEBUG version.parse: attempting to parse string '0.1.0-dev.1' as       version.py:126
                    Version                                                                                                                 
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed prerelease_token dev, prerelease_revision  version.py:140
                    1 from version string 0.1.0-dev.1                                                                                       
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed build metadata '' from version string      version.py:151
                    0.1.0-dev.1                                                                                                             
           DEBUG    [semantic_release.version.version] DEBUG version.parse: attempting to parse string '0.1.0-dev.10' as      version.py:126
                    Version                                                                                                                 
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed prerelease_token dev, prerelease_revision  version.py:140
                    10 from version string 0.1.0-dev.10                                                                                     
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed build metadata '' from version string      version.py:151
                    0.1.0-dev.10                                                                                                            
[... snip for GH character limit ...]
           DEBUG    [semantic_release.version.version] DEBUG version.parse: attempting to parse string '1.0.1-dev.1' as       version.py:126
                    Version                                                                                                                 
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed prerelease_token dev, prerelease_revision  version.py:140
                    1 from version string 1.0.1-dev.1                                                                                       
           DEBUG    [semantic_release.version.version] DEBUG version.parse: parsed build metadata '' from version string      version.py:151
                    1.0.1-dev.1                                                                                                             
           DEBUG    [semantic_release.version.version] DEBUG version.parse: attempting to parse string 'azure-0.1.0' as       version.py:126
                    Version                                                                                                                 
Traceback (most recent call last):
  File "/.../bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "/.../lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/.../lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/.../lib/python3.10/site-packages/semantic_release/cli/commands/version.py", line 274, in version
    new_version = next_version(
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 224, in next_version
    all_git_tags_as_versions = tags_and_versions(repo.tags, translator)
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 37, in tags_and_versions
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/.../lib/python3.10/site-packages/semantic_release/version/algorithm.py", line 37, in <listcomp>
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/.../lib/python3.10/site-packages/semantic_release/version/translator.py", line 75, in from_tag
    return self.from_string(raw_version_str)
  File "/.../lib/python3.10/site-packages/semantic_release/version/translator.py", line 56, in from_string
    return Version.parse(
  File "/.../lib/python3.10/site-packages/semantic_release/version/version.py", line 129, in parse
    raise InvalidVersion(f"{version_str!r} is not a valid Version")
semantic_release.version.version.InvalidVersion: 'azure-0.1.0' is not a valid Version
```

**Comment by bernardcooke53** [comment]
This should be addressed in 8.0.1 :crossed_fingers:
