### ISSUE TITLE
Failing to validate version_toml

### ISSUE THREAD

**Issue by shooit** [python-semantic-release/python-semantic-release#629]
## The problem

version 8.x is failing to parse `version_toml` from the pyproject.toml file with input that was working for version 7.x

## Expected behavior

Per the [documentation](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-toml), I would not expect any changes to this configuration 

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version 
Python 3.11.3

pip --version 
pip 22.3 from /Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/pip (python 3.11)

semantic-release --version 
semantic-release, version 8.0.0

pip freeze
appnope==0.1.3
argcomplete==3.0.8
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
black==23.7.0
blinker==1.6.2
cachetools==5.3.0
cattrs==22.2.0
certifi==2023.5.7
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.1.0
click==8.1.3
colorlog==6.7.0
decorator==5.1.1
Deprecated==1.2.14
deptry==0.12.0
distlib==0.3.6
dotty-dict==1.3.1
executing==1.2.0
filelock==3.12.1
flake8==6.0.0
Flask==2.3.2
gitdb==4.0.10
GitPython==3.1.31
google-api-core==2.11.0
google-auth==2.19.1
google-cloud-iam==2.12.0
google-cloud-monitoring==2.15.0
google-cloud-secret-manager==2.16.2
google-cloud-trace==1.11.1
googleapis-common-protos==1.59.0
grpc-google-iam-v1==0.12.6
grpcio==1.54.2
grpcio-status==1.54.2
identify==2.5.24
idna==3.4
importlib-metadata==6.0.1
importlib-resources==5.7.0
iniconfig==2.0.0
ipython==8.14.0
isort==5.12.0
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
jsii==1.84.0
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-dataclass==8.5.14
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
mypy-extensions==1.0.0
nodeenv==1.8.0
nox==2023.4.22
opentelemetry-api==1.18.0
opentelemetry-exporter-gcp-monitoring==1.5.0a0
opentelemetry-exporter-gcp-trace==1.5.0
opentelemetry-propagator-gcp==1.5.0
opentelemetry-resourcedetector-gcp==1.5.0a0
opentelemetry-sdk==1.18.0
opentelemetry-semantic-conventions==0.39b0
packaging==23.1
parso==0.8.3
pathspec==0.11.1
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.5.1
pluggy==1.0.0
pre-commit==3.3.3
projen==0.71.136
prompt-toolkit==3.0.38
proto-plus==1.22.2
protobuf==4.23.2
ptyprocess==0.7.0
publication==0.0.3
pula-jwt==0.2.2
pula-projen==3.6.4
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pydantic==1.10.11
pyflakes==3.0.1
Pygments==2.15.1
pyright==1.1.317
pytest==7.4.0
pytest-custom-exit-code==0.3.0
pytest-dotenv==0.5.2
pytest-mock==3.11.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-gitlab==3.14.0
python-semantic-release==8.0.0
PyYAML==6.0
requests==2.31.0
requests-toolbelt==1.0.0
rich==13.4.2
rsa==4.9
-e git+ssh://git@github.com/pulacapital/serverless-tools.git@e6070864a1f9cd92b944e8d22c17c9744e6a14fc#egg=serverless_tools
shellingham==1.5.0.post1
six==1.16.0
smmap==5.0.0
stack-data==0.6.2
toml==0.10.2
tomlkit==0.11.8
traitlets==5.9.0
typeguard==2.13.3
typing-inspect==0.8.0
typing_extensions==4.6.3
urllib3==1.26.16
virtualenv==20.23.0
wcwidth==0.2.6
Werkzeug==2.3.3
wrapt==1.15.0
zipp==3.15.0
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

I am using poetry v1.5.1

## Configuration

Please add your `semantic-release` configuration, and if applicable also provide
your `build-system` configuration from `pyproject.toml`.

```
[tool.poetry]
version = "0.19.3"
description = ""
authors = [ ]
readme = "README.md"
name = "serverless_tools"

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
branch = "main"
upload_to_repository = false
commit_subject = "chore(release): {version} [skip ci]"
version_source = "tag"
commit_version_number = true
build_command = "poetry build"
upload_to_release = true
```
## Logs

Please provide debug logs for the command you are using with the `-vv` flag, e.g.

```shell
semantic-release -vv --noop version

Traceback (most recent call last):
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/bin/semantic-release", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/serverless-tools-hpJnRa-7-py3.11/lib/python3.11/site-packages/semantic_release/cli/commands/main.py", line 140, in main
    raw_config = RawConfig.parse_obj(config_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RawConfig
version_toml
  value is not a valid tuple (type=type_error.tuple)

```

If using GitHub actions, ensure the `root_options` contains the `-vv` flag
for verbosity, and attach your workflow definition.

## Additional context

_Add any other information that could be useful, such as a link to your project
(if public), links to a failing GitHub Action, or an example commit._

**Comment by xec-abailey** [comment]
Hit this as well, just to state the solution outright I changed this: 

```
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
```

To this: 

 ```
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
```

As indicated in the [docs here](https://github.com/python-semantic-release/python-semantic-release/blob/master/docs/configuration.rst#version_toml-liststr) and the ci action worked again. 

Thankss @browniebroke  and @shooit

**Comment by shooit** [comment]
Thanks for the info, and it looks like RTD is updated now too. Appreciate the help @browniebroke
