### ISSUE TITLE
Get currently version after update to V8

### ISSUE THREAD

**Issue by rodrigosfelix** [python-semantic-release/python-semantic-release#648]
After the update to V8, my github action not get the currently version of my library. How can I continue release from the currently version? 

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/semantic-release/semantic_release/__main__.py", line 6, in <module>
    main(args=sys.argv[1:])
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/semantic-release/semantic_release/cli/commands/version.py", line 274, in version
    new_version = next_version(
  File "/semantic-release/semantic_release/version/algorithm.py", line [22](https://github.com/devcotefacil/cotefacilib/actions/runs/5614749820/job/15213531422#step:7:23)4, in next_version
    all_git_tags_as_versions = tags_and_versions(repo.tags, translator)
  File "/semantic-release/semantic_release/version/algorithm.py", line [37](https://github.com/devcotefacil/cotefacilib/actions/runs/5614749820/job/15213531422#step:7:38), in tags_and_versions
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/semantic-release/semantic_release/version/algorithm.py", line 37, in <listcomp>
    ts_and_vs = [(t, translator.from_tag(t.name)) for t in tags]
  File "/semantic-release/semantic_release/version/translator.py", line 71, in from_tag
    raise ValueError(
ValueError: Tag '0.1.0' doesn't match tag format 'v{version}'
```

**Comment by bernardcooke53** [comment]
Hi @rodrigosfelix :wave: 

Are your git tags "vX.Y.Z", "X.Y.Z" or a mixture of both? It looks as though you need to change the `tag_format` [configuration setting](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#tag-format-str):

* If the tags are "X.Y.Z" then set `tag_format = "{version}"`
* If the tags are a mixture, try setting `tag_format = "v?{version}"`
