### ISSUE TITLE
Gitlab CI : Error while retrieving branch name

### ISSUE THREAD

**Issue by VRohou** [python-semantic-release/python-semantic-release#701]
## The problem

Since python-semantic-release v8, all my Gitlab CI pipeline are failing.
It seems it's failing when semantic-release is trying to retrieve the branch name, to choose the appropriate configuration.

But, from what I understood, Gitlab perform a checkout on a commit and not a branch, so the git repository is in a detached state, preventing git-python from retrieving the current branch name.

Am I doing something wrong ? Or do I need to tweak my Gitlab CI to manually checkout the branch and reset to the specific commit ?

## Expected behavior

Semantic-Release able to retrieve git branch name.
Or having a documented solution  to work with Gitlab.

## Environment

Gitlab CI
Gitlab Runner 15.3.0

## Logs

```shell

semantic-release --noop version
🛡 You are running in no-operation mode, because the '--noop' flag was supplied
Traceback (most recent call last):
  File "/usr/local/bin/semantic-release", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_release/cli/commands/main.py", line 147, in main
    runtime = RuntimeContext.from_raw_config(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_release/cli/config.py", line 261, in from_raw_config
    branch_config = cls.select_branch_options(raw.branches, repo.active_branch.name)
                                                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/base.py", line 896, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 309, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'c630d237f6d975166f5457fae06f0631440f2328'
```

**Comment by domste** [comment]
same problem here.

**Comment by VRohou** [comment]
To workaround this issue, I added the following lines to my semantic-release steps in my GitLab CI : 

```
git branch --force $CI_COMMIT_BRANCH $CI_COMMIT_SHA
git checkout $CI_COMMIT_BRANCH
```

Right before the semantic-release commands. And it worked well.

**Comment by damnmso** [comment]
same problem here

**Comment by benedikt-bartscher** [comment]
Same here with semantic-release v8.0.8 and gitlab v16.3.2-ee

**Comment by bernardcooke53** [comment]
Unfortunately this is a general problem with CI services that checkout your repo by commit hash - because PSR has to create a new commit to update versions etc, it needs a branch to commit that to. v7 used to silently checkout master and commit to that branch, we can't do that any more to support multi-branch releases. As @VRohou and @damnmso said - you need to checkout a branch first.
