### ISSUE TITLE
GitHub action raises stderr: 'error: src refspec main matches more than one

### ISSUE THREAD

**Issue by kierun** [python-semantic-release/python-semantic-release#843]
## The problem

While attempting to use the GHA semantic release, I got this error: `stderr: 'error: src refspec main matches more than one`

Full trace:

```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/semantic-release/semantic_release/__main__.py", line 6, in <module>
    main(args=sys.argv[1:])
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/semantic-release/semantic_release/cli/commands/version.py", line 544, in version
    repo.git.push(remote_url, active_branch)
  File "/semantic-release/.venv/lib/python3.10/site-packages/git/cmd.py", line 800, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/git/cmd.py", line 1386, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/git/cmd.py", line 1183, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push ***github.com/kierun/pynpc.git main
  stderr: 'error: src refspec main matches more than one
error: failed to push some refs to 'https://github.com/kierun/pynpc.git''
```

## Expected behavior

I expected it to create a new patch release.

## Environment

I am using the GHA with poetry.

[Full action results with `-vv` here](https://github.com/kierun/pynpc/actions/runs/7988462759/job/21813086354)

## Configuration

From `pyproject.toml`:

```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"
```

## Logs

[Full action results with `-vv` here](https://github.com/kierun/pynpc/actions/runs/7988462759/job/21813086354)

## Additional context

- [pynpc project](https://github.com/kierun/pynpc)
- [GHA yaml](https://github.com/kierun/pynpc/blob/main/.github/workflows/on-release-main.yml)
- I am :100: happy to test things.

**Comment by codejedi365** [comment]
@kierun, although PSR shouldn't be throwing a full stack trace at you from a hard exception, this failure comes from a underlying issue with your repository.  Basically at the point in your log, it's running a git push of the new version commit that PSR makes and attempts to push it to the repository. This action fails due to the git application throwing an exit code. Please try the steps in this article: https://confluence.atlassian.com/bitbucketserverkb/pushing-a-branch-to-bitbucket-fails-with-the-error-refspec-matches-more-than-one-1108091938.html

I couldn't see anything that stood out when I looked at your repo. Check your branches and tags in the remote for duplicates or partial leading text matches.

**Comment by kierun** [comment]
This is the result:

```bash
√ pynpc-nZSnSxFl-py3.12(main|✓); git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/main
√ pynpc-nZSnSxFl-py3.12(main|✓); git branch | rg -i "main"
* main
√ pynpc-nZSnSxFl-py3.12(main|✓); git ls-remote --heads | rg -i "main"
From git@kierun.github.com:kierun/pynpc.git
4405a6097604f7f99985e38a29946bafc49b3c36        refs/heads/main
√ pynpc-nZSnSxFl-py3.12(main|✓); git tag | rg -i "v"
v0.1.0
v0.2.0
√ pynpc-nZSnSxFl-py3.12(main|✓); git ls-remote --tags | rg -i "v"
From git@kierun.github.com:kierun/pynpc.git
446aff32799fd4ff7f81a1436e143792fe360bf4        refs/tags/v0.1.0
7e1505e956c56b866246cdb82b41cfccd43dbe75        refs/tags/v0.1.0^{}
7aa0969d8191e8bbc33419a89197e8bd1bfe2839        refs/tags/v0.2.0
586a49c8686b9b82da0226736f214753c3905eea        refs/tags/v0.2.0^{}
```

This looks fine as far as I can tell. However, looking into it a little more, I found this:

```bash
√ pynpc-nZSnSxFl-py3.12(main|✓); git tag
main
v0.1.0
v0.2.0
√ pynpc-nZSnSxFl-py3.12(main|✓); git tag -d main
Deleted tag 'main' (was 7e1505e)
√ pynpc-nZSnSxFl-py3.12(main|✓); git push origin :refs/tags/main
To kierun.github.com:kierun/pynpc.git
 - [deleted]         main
 - 
 ```

[It worked!](https://github.com/kierun/pynpc/actions/runs/8002172824) 

I am going to leave this here in case someone else stumbles on the same issue. 

@codejedi365 Thank you very much for your help. It is appreciated.

**Comment by codejedi365** [comment]
Awesome, good work
