### ISSUE TITLE
branches.match value "*" causes unintentional error

### ISSUE THREAD

**Issue by b0lle** [python-semantic-release/python-semantic-release#931]
## The problem

If one sets the matches value of semantic_release.branches.main.match property to "*", the --version command fails with an confusing error message.
```toml
[semantic_release.branches.main]
match = "*"
prerelease_token = "rc"
prerelease = false
```
causes
```
semantic-release -vv version
[14:51:17] DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: logging level set to: DEBUG  main.py:105
           DEBUG    [git.util] DEBUG util.is_cygwin_git: Failed checking if running in CYGWIN due to:  util.py:469
                    FileNotFoundError(2, 'No such file or directory')
           DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: global cli options:          main.py:123
                    GlobalCommandLineOptions(noop=False, verbosity=2, config_file='pyproject.toml',
                    strict=False)
           INFO     [semantic_release.cli.util] INFO util.load_raw_config_file: Loading configuration   util.py:78
                    from pyproject.toml
           DEBUG    [semantic_release.cli.util] DEBUG util.load_raw_config_file: Trying to parse        util.py:81
                    configuration pyproject.toml in TOML format

Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.10.11/bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/semantic_release/cli/commands/main.py", line 148, in main
    runtime = RuntimeContext.from_raw_config(
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/semantic_release/cli/config.py", line 306, in from_raw_config
    branch_config = cls.select_branch_options(raw.branches, active_branch)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/site-packages/semantic_release/cli/config.py", line 263, in select_branch_options
    if re.match(options.match, active_branch):
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/julianfrenzel/.pyenv/versions/3.10.11/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/Users//.pyenv/versions/3.10.11/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

this error message is related to the * operator in the re package https://docs.python.org/3/library/re.html. The issue here is that * tries to repeat from the preceding regular expression, which is not given in this case.
## Expected behavior

A brief validation of the matches property would be great.

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version 
3.10.11
pip --version
23.0.1
semantic-release --version
semantic-release, version 9.7.3
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.
poetry v1.6.1

## Configuration

```
  72   │ [tool.semantic_release]
  73   │ version_toml = [
  74   │     "pyproject.toml:tool.poetry.version",
  75   │ ]
  76   │ version_variables = [
  77   │     "src/package_name/__init__.py:__version__",
  78   │ ]
  79   │
  80   │ [tool.semantic_release.branches.main]
  81   │ # semantic-releases makes a dry-run, so the branch name does not matter
  82   │ match = "*"
```

**Comment by codejedi365** [comment]
@b0lle, thank you for the report. I believe you understand why but `*` alone is not a valid python regular expression which is the reason for the exception and the ugly python default stacktrace.  However, for usability sake I do understand the likelihood of the use of just `*` means all to us developers and we should be catching the exception from `re` regardless.

I can add a validation step via `re.compile` and try to provide a more understandable error message if a user hits this error again.  I might be inclined to add a quick transformer for that single case of `*` to `.*` but I need to think on it further.

**Comment by codejedi365** [comment]
Still in the backlog but still desired for completion.

**Comment by codejedi365** [comment]
Still in backlog
