### ISSUE TITLE
KeyError: 'changelog' when running in GitHub actions

### ISSUE THREAD

**Issue by alexdivet** [python-semantic-release/python-semantic-release#999]
### Description

I'm trying to run `python-semantic-release` in GitHub action but hit the error below

I have no issue running this locally using `semantic-release version`.

### Expected behavior

The GitHub action step to succeed.

### Actual behavior

The error shared above and my GitHub action step failing.

### Environment

-  **Operating System (w/ version):** Default GitHub action server Ubuntu 22.04.4 LTS
-  **Python version:** Defined from building `Build container for action use: '/home/runner/work/_actions/python-semantic-release/python-semantic-release/v9.8.6/Dockerfile'.`: python:3.12
-  **Semantic-release version:** v9.8.6

## Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]
commit_message = "chore(release): {version} [skip ci]"

[tool.semantic_release.branches.prod]
match = "prod"
prerelease = false
```

</details>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml
jobs:
    semantic-release:
        name: Create a semantic release note
        runs-on: ubuntu-latest
        permissions:
            packages: write
            id-token: write
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: prod
                  fetch-depth: 0

            - name: Release & publish to GitHub
              uses: python-semantic-release/python-semantic-release@v9.8.6
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv version</code></summary>

```log
[08:29:34] INFO     [semantic_release.cli.util] INFO                  util.py:79
                    util.load_raw_config_file: Loading configuration            
                    from pyproject.toml                                         
           INFO     [semantic_release.cli.config] INFO             config.py:414
                    config.select_branch_options: Using group                   
                    '***' options, as '***' matches '***'                    
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 0                        
                    previous tags                                               
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:282
                    algorithm.next_version: Found 0 full                        
                    releases (excluding prereleases)                            
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:324
                    algorithm.next_version: No full releases                    
                    have been made yet, the default version to                  
                    use is 0.0.0                                                
[08:29:35] INFO     [semantic_release.version.algorithm] INFO   algorithm.py:131
                    algorithm._bfs_for_latest_version_in_histor                 
                    y: no version tags found in this branch's                   
                    history                                                     
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:358
                    algorithm.next_version: The last full                       
                    version in this branch's history was None                   
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:4[33](https://github.com/Edelman-DxI/trust-stream-backend/actions/runs/10316154437/job/28557760295#step:7:34)
                    algorithm.next_version: The type of the                     
                    next release release is: minor                              
0.1.0
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 0                        
                    previous tags                                               
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 0                        
                    previous tags                                               
The next version is: 0.1.0! 🚀
           INFO     [semantic_release.cli.changelog_writ changelog_writer.py:137
                    er] INFO                                                    
                    changelog_writer.write_changelog_fil                        
                    es: No contents found in                                    
                    '/github/workspace/templates', using                        
                    default changelog template                                  
           INFO     [semantic_release.version.declaration]    declaration.py:121
                    INFO declaration.replace: found                             
                    'tool.poetry.version' in source file                        
                    contents, replacing with 0.1.0                              
No build command specified, skipping
Traceback (most recent call last):
  File "/psr/.venv/bin/semantic-release", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 14[34](https://github.com/Edelman-DxI/trust-stream-backend/actions/runs/10316154437/job/28557760295#step:7:35), in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/commands/version.py", line 657, in version
    message=commit_message.format(version=new_version),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'changelog'
```

</details>

**Comment by codejedi365** [comment]
Thanks for the report. I'm not seeing anything obvious off the bat, I'll keep looking.

**Comment by codejedi365** [comment]
@alexdivet, were you able to fix your issue on your own?  

I don't seem to have enough information to track down a bug here.  The stack trace you provided leads me to believe that the `semantic_release.commit_message` property has the syntax `{changelog}` in it  which I have demonstrated that a key error would occur on that same line 657. Example:

```python
>>> "commit message {version} {changelog}".format(version="v1.2.3")
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
# KeyError: 'changelog'
```

However, the configuration you provided states that the `commit_message` value is `"chore(release): {version} [skip ci]"`.  This would not make the same error. 

Ultimately, I cannot replicate your issue. If you could provide a link to your github action log maybe I could dig deeper. Sorry for the inconvenience.
